config/routes.rb
Rails.application.routes.draw do
  resources :devises

   root 'devises#index'

end

app/models/devise.rb
# == Schema Information
#
# Table name: devises
#
#  id         :integer          not null, primary key
#  password   :string(255)
#  email      :string(255)
#  put_id     :integer
#  created_at :datetime
#  updated_at :datetime
#

class Devise < ActiveRecord::Base
  belongs_to :put
  # has_one :u, through: :put

  accepts_nested_attributes_for :put

  validates :password , presence: { message: 'es requerido'}
  validates :email ,  presence: { message: 'es requerido'}
  # validates_presence_of :put
  # validates_associated :put
end

app/models/put.rb
# == Schema Information
#
# Table name: puts
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  apellido   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Put < ActiveRecord::Base
  has_one :u
  accepts_nested_attributes_for :u
  # validates_associated :put
  validates :nombre , presence: { message: 'es requerido'}
  validates :apellido ,  presence: { message: 'es requerido'}
end

app/models/u.rb
# == Schema Information
#
# Table name: us
#
#  id         :integer          not null, primary key
#  cargo      :string(255)
#  apodo      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  put_id     :integer
#

class U < ActiveRecord::Base
  belongs_to :put
  validates :cargo , presence: { message: 'es requerido'}
  validates :apodo , presence: { message: 'es requerido'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devises_controller.rb
class DevisesController < ApplicationController
  before_action :set_devise, only: [:show, :edit, :update, :destroy]

  # GET /devises
  # GET /devises.json
  def index
    @devises = Devise.all
  end

  # GET /devises/1
  # GET /devises/1.json
  def show
  end

  # GET /devises/new
  def new
    @devise = Devise.new
    p = @devise.build_put
    p.build_u
  end

  # GET /devises/1/edit
  def edit
  end

  # POST /devises
  # POST /devises.json
  def create
    @devise = Devise.new(devise_params)

    respond_to do |format|
      if @devise.save
        format.html { redirect_to @devise, notice: 'Devise was successfully created.' }
        format.json { render :show, status: :created, location: @devise }
      else
        format.html { render :new }
        format.json { render json: @devise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devises/1
  # PATCH/PUT /devises/1.json
  def update
    respond_to do |format|
      if @devise.update(devise_params)
        format.html { redirect_to @devise, notice: 'Devise was successfully updated.' }
        format.json { render :show, status: :ok, location: @devise }
      else
        format.html { render :edit }
        format.json { render json: @devise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devises/1
  # DELETE /devises/1.json
  def destroy
    @devise.destroy
    respond_to do |format|
      format.html { redirect_to devises_url, notice: 'Devise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devise
      @devise = Devise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def devise_params
      params.require(:devise).permit(:password, :email, put_attributes: [:nombre,:apellido,u_attributes:[:cargo,:apodo]])
    #    pets_attributes: [ :name, :category ] put_attributes
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devises_helper.rb
module DevisesHelper
end

app/views/devises/_form.html.erb
<%= form_for(@devise) do |f| %>
    <% if @devise.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@devise.errors.count, "error") %> prohibited this devise from being saved:</h2>

          <ul>
            <% @devise.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h2> Campos de Devise</h2>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <h2>Campos de Put</h2>
    <%= f.fields_for :put do |p| %>
        <%= p.label :nombre %><br>
        <%= p.text_field :nombre %>
        <%= p.label :apellido %><br>
        <%= p.text_field :apellido %>

        <h2>Campos de U</h2>
        <%= p.fields_for :u do |u| %>
            <%= u.label :cargo %><br>
            <%= u.text_field :cargo %>
            <%= u.label :apodo %><br>
            <%= u.text_field :apodo %>

        <%end%>
    <%end %>



    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/devises/edit.html.erb
<h1>Editing devise</h1>

<%= render 'form' %>

<%= link_to 'Show', @devise %> |
<%= link_to 'Back', devises_path %>

app/views/devises/index.html.erb
<h1>Listing devises</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th>Put</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devises.each do |devise| %>
      <tr>
        <td><%= devise.password %></td>
        <td><%= devise.email %></td>
        <td><%= devise.put %></td>
        <td><%= link_to 'Show', devise %></td>
        <td><%= link_to 'Edit', edit_devise_path(devise) %></td>
        <td><%= link_to 'Destroy', devise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Devise', new_devise_path %>

app/views/devises/new.html.erb
<h1>New devise</h1>

<%= render 'form' %>

<%= link_to 'Back', devises_path %>

app/views/devises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @devise.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @devise.email %>
</p>

<p>
  <strong>Put:</strong>
  <%= @devise.put %>
</p>

<%= link_to 'Edit', edit_devise_path(@devise) %> |
<%= link_to 'Back', devises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedPrueba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>